"""
state.py — Agent state for LangGraph.

LangGraph agents are state machines. This defines the state
that flows through the graph nodes.
"""

from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """State passed between LangGraph nodes."""
    # Chat messages (HumanMessage, AIMessage, ToolMessage)
    # add_messages is a reducer that appends new messages to the list
    messages: Annotated[list, add_messages]

    # Context about loaded data (column names, dtypes, shape)
    data_context: str

    # Summary of existing notebook cells
    notebook_summary: str

    # Code generated by the agent (to be inserted into notebook)
    generated_code: str | None
