"""
tools.py — Agent tools for the v2 conversational copilot.

v1 tools: 8 fixed pipeline tools that DO the ML work directly.
v2 tools: tools that GENERATE CODE for the user to run in Jupyter.

The key insight: in v2, the agent doesn't run sklearn directly.
Instead, it generates Python code that the user runs in their notebook.
This is transparent and educational.
"""

import ast

from langchain_core.tools import tool


@tool
def generate_code(instruction: str) -> str:
    """
    Generate Python code based on the user's instruction.
    The code will be inserted into a new Jupyter notebook cell.

    Args:
        instruction: what the user wants to do (e.g., "plot age vs salary")

    Returns:
        Python code string ready to be inserted into a notebook cell.
    """
    # This tool is special — it's actually handled by the LLM itself.
    # The LLM generates the code as part of its response.
    # This tool definition exists so LangGraph knows the agent can generate code.
    # The actual code generation happens in the graph's generate node.
    return f"# Code will be generated by the LLM for: {instruction}"


@tool
def read_dataframe_info(variable_name: str) -> str:
    """
    Generate code to inspect a DataFrame's schema, shape, and sample data.
    Use this when the user uploads data or asks about the data structure.

    Args:
        variable_name: name of the DataFrame variable (usually 'df')

    Returns:
        Python code that prints DataFrame info.
    """
    return f"""# Inspect the dataset
print(f"Shape: {{{variable_name}.shape}}")
print(f"\\nColumns and types:")
print({variable_name}.dtypes)
print(f"\\nFirst 5 rows:")
display({variable_name}.head())
print(f"\\nMissing values:")
print({variable_name}.isnull().sum())
print(f"\\nBasic statistics:")
display({variable_name}.describe())"""


@tool
def create_visualization(plot_type: str, columns: list[str], title: str = "") -> str:
    """
    Generate Plotly visualization code for interactive charts in Jupyter.

    Plotly charts are interactive — users can zoom, pan, hover for values,
    and export as PNG. Much better than static matplotlib in notebooks.

    Args:
        plot_type: type of plot (scatter, histogram, bar, boxplot, heatmap, line, pie, violin, sunburst)
        columns: column names to plot
        title: optional chart title

    Returns:
        Python code for an interactive Plotly visualization.
    """
    title_str = title or f"{plot_type.title()} Plot"

    if plot_type == "scatter" and len(columns) >= 2:
        return f"""import plotly.express as px

fig = px.scatter(df, x='{columns[0]}', y='{columns[1]}',
                 title='{title_str}',
                 opacity=0.6,
                 template='plotly_dark')
fig.update_layout(width=800, height=500)
fig.show()"""

    elif plot_type == "histogram" and len(columns) >= 1:
        return f"""import plotly.express as px

fig = px.histogram(df, x='{columns[0]}',
                   title='{title_str}',
                   nbins=30,
                   template='plotly_dark')
fig.update_layout(width=800, height=500)
fig.show()"""

    elif plot_type == "boxplot" and len(columns) >= 1:
        if len(columns) == 1:
            return f"""import plotly.express as px

fig = px.box(df, y='{columns[0]}',
             title='{title_str}',
             template='plotly_dark')
fig.update_layout(width=800, height=500)
fig.show()"""
        else:
            cols_list = columns[:5]
            return f"""import plotly.express as px

melted = df[{cols_list}].melt(var_name='Feature', value_name='Value')
fig = px.box(melted, x='Feature', y='Value',
             title='{title_str}',
             template='plotly_dark')
fig.update_layout(width=800, height=500)
fig.show()"""

    elif plot_type == "heatmap":
        return f"""import plotly.express as px

corr = df.select_dtypes(include='number').corr()
fig = px.imshow(corr,
                text_auto='.2f',
                title='{title_str}',
                color_continuous_scale='RdBu_r',
                aspect='auto',
                template='plotly_dark')
fig.update_layout(width=800, height=600)
fig.show()"""

    elif plot_type == "bar" and len(columns) >= 1:
        return f"""import plotly.express as px

counts = df['{columns[0]}'].value_counts().head(20).reset_index()
counts.columns = ['{columns[0]}', 'count']
fig = px.bar(counts, x='{columns[0]}', y='count',
             title='{title_str}',
             template='plotly_dark')
fig.update_layout(width=800, height=500)
fig.show()"""

    elif plot_type == "line" and len(columns) >= 1:
        y_col = columns[0]
        x_part = f"x='{columns[1]}', " if len(columns) >= 2 else ""
        return f"""import plotly.express as px

fig = px.line(df, {x_part}y='{y_col}',
              title='{title_str}',
              template='plotly_dark')
fig.update_layout(width=800, height=500)
fig.show()"""

    elif plot_type == "pie" and len(columns) >= 1:
        return f"""import plotly.express as px

counts = df['{columns[0]}'].value_counts().head(10).reset_index()
counts.columns = ['{columns[0]}', 'count']
fig = px.pie(counts, names='{columns[0]}', values='count',
             title='{title_str}',
             template='plotly_dark')
fig.update_layout(width=700, height=500)
fig.show()"""

    elif plot_type == "violin" and len(columns) >= 1:
        return f"""import plotly.express as px

fig = px.violin(df, y='{columns[0]}',
                box=True, points='outliers',
                title='{title_str}',
                template='plotly_dark')
fig.update_layout(width=800, height=500)
fig.show()"""

    else:
        return f"""import plotly.express as px

# {title_str}
fig = px.scatter(df, x='{columns[0] if columns else "index"}',
                 y='{columns[1] if len(columns) > 1 else columns[0] if columns else "index"}',
                 title='{title_str}',
                 template='plotly_dark')
fig.update_layout(width=800, height=500)
fig.show()"""


@tool
def train_model(model_type: str, target_column: str, feature_columns: list[str] | None = None) -> str:
    """
    Generate scikit-learn model training code.

    Args:
        model_type: model name (random_forest, logistic_regression, xgboost, linear_regression, lightgbm)
        target_column: the column to predict
        feature_columns: columns to use as features (None = all except target)

    Returns:
        Python code for preprocessing, training, and evaluation.
    """
    features_code = (
        f"feature_cols = {feature_columns}"
        if feature_columns
        else f"feature_cols = [c for c in df.columns if c != '{target_column}']"
    )

    model_imports = {
        "random_forest": ("from sklearn.ensemble import RandomForestClassifier", "RandomForestClassifier(n_estimators=100, random_state=42)"),
        "logistic_regression": ("from sklearn.linear_model import LogisticRegression", "LogisticRegression(max_iter=1000, random_state=42)"),
        "xgboost": ("from xgboost import XGBClassifier", "XGBClassifier(n_estimators=100, random_state=42, verbosity=0)"),
        "linear_regression": ("from sklearn.linear_model import LinearRegression", "LinearRegression()"),
        "lightgbm": ("from lightgbm import LGBMClassifier", "LGBMClassifier(n_estimators=100, random_state=42, verbosity=-1)"),
        "random_forest_regressor": ("from sklearn.ensemble import RandomForestRegressor", "RandomForestRegressor(n_estimators=100, random_state=42)"),
    }

    model_key = model_type.lower().replace(" ", "_")
    import_line, model_line = model_imports.get(model_key, (
        "from sklearn.ensemble import RandomForestClassifier",
        "RandomForestClassifier(n_estimators=100, random_state=42)",
    ))

    return f"""from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder
import pandas as pd
{import_line}

# Prepare features and target
{features_code}
X = df[feature_cols].copy()
y = df['{target_column}'].copy()

# Handle missing values
X = X.fillna(X.median(numeric_only=True))
for col in X.select_dtypes(include='object').columns:
    X[col] = LabelEncoder().fit_transform(X[col].fillna('missing'))

# Encode target if categorical
if y.dtype == 'object':
    le = LabelEncoder()
    y = le.fit_transform(y)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = {model_line}
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print(f"Accuracy: {{accuracy_score(y_test, y_pred):.4f}}")
print("\\nClassification Report:")
print(classification_report(y_test, y_pred))"""


def validate_code(code: str) -> bool:
    """Check if generated code is valid Python syntax."""
    try:
        ast.parse(code)
        return True
    except SyntaxError:
        return False
